[jumpbox]
jumpbox ansible_host=192.168.121.10

[controlplane]
server ansible_host=192.168.121.11

[workers]
node-0 ansible_host=192.168.121.12
node-1 ansible_host=192.168.121.13

[nodes:children]
controlplane
workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
